<a href="https://colab.research.google.com/github/McPetzka/ML-exercises/blob/main/ANN_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [5]:
tf.__version__

'2.3.0'

In [6]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
ann=tf.keras.models.Sequential()


In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [18]:
ann.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

In [19]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7625 - accuracy: 0.5495
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5245 - accuracy: 0.7972
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4596 - accuracy: 0.8235
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4321 - accuracy: 0.8251
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4168 - accuracy: 0.8292
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4053 - accuracy: 0.8342
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3953 - accuracy: 0.8391
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3865 - accuracy: 0.8438
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3788 - accuracy: 0.8459
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3720 - accura

In [20]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [21]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1525   70]
 [ 200  205]]


0.865